name: wayland-debug
version: git
summary: Wayland debugging toolkit
description: |
  wayland-debug is a command line tool that can be used to view Wayland messages with syntax
  highlighting, filter them, even set breakpoints on specific messages (when run as a GDB plugin)
license: MIT
base: core20
confinement: classic
grade: stable

parts:
  libffi:
    # By compiling a custom libffi we can force it to be statically linked
    plugin: autotools
    source: https://github.com/libffi/libffi.git
    source-tag: v3.4.2
    build-packages:
      - libltdl-dev
      - texinfo
    autotools-configure-parameters: [--disable-shared, --enable-static, CFLAGS='-fPIC']
    # Since we are statically linking, we don't want to prime anything
    prime:
      - -usr/

  wayland-debug:
    after: [libffi]
    plugin: dump
    source: https://github.com/wmww/wayland-debug.git
    prime:
      - -**/.github
      - -**/test
      - -**/.gitignore
      - -**/libwayland_debug_logs
      - -**/update-protocols.sh
    # python3 dependency is provided by the core20 base
    override-build: |
      snapcraftctl build
      apt remove meson
      # Install from pip so we get a version new enough to work
      pip3 install meson ninja
      "$SNAPCRAFT_PART_INSTALL/resources/get-libwayland.sh"
      "$SNAPCRAFT_PART_INSTALL/resources/remove-libwayland-build-files.sh"
    build-packages:
      - python3-pip
      - debhelper
      - libexpat1-dev
      - pkg-config
    build-attributes:
      # Our libwayland will be dynamically linked to by a system binary, so we need to use the
      # system libc. This is fragile, but seems to generally work at least on distros not older than
      # the snap base (Ubuntu 20.04)
      - no-patchelf

apps:
  wayland-debug:
    command: main.py
